server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/db_smartfix_reparaciones
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=smartfix-secret-key-256-bits-minimo-para-hs256-aqui
jwt.expiration-ms=3600000

# URL del microservicio de clientes (en docker usa el nombre del servicio)

services.cliente.url=http://ms-cliente:8081
