server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_smartfix_clientes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=smartfix-secret-key-256-bits-minimo-para-hs256-aqui
jwt.expiration-ms=3600000zº